README.md, examples/simple/main.tf, main.tf, variables.tf
_plays beginning of evanesence's my immortal_
What the title says.
=> Create an explicit input variable to not use sns topic

sleuth/sleuth/auditor.py
Slowly fixing bugs I encounter. Sigh.
=> Conversion of strings to int for ages

LICENSE
Add the standard license to the repo. Do we want this one or MIT license?
=> Add Apache License 2.0 to the repo

.circleci/config.yml, scripts/release
Some quick fixes that weren't handled in this PR https://github.com/trussworks/aws-iam-sleuth/pull/30
=> Fix build and release

.circleci/config.yml, scripts/build, scripts/release
release was failing because it ran on every merge to master
=> updates to circleci config to move releases out of every merge

.circleci/config.yml
Part of 
See img here: 
https://hub.docker.com/layers/trussworks/ghr/391c83e041d5467164631f7e5be2fa00b46e14a7/images/sha256-2acceb3e815c0f71a315254689794b889c0e2de0e66984d19091f21de6b3bc73?context=repo
=> Mdawn update ghr image

.circleci/config.yml
=> updated circleci config

.circleci/config.yml, README.md, scripts/release
- updates circleci configuration to use new gh cli
- updates scripts/release to use the gh cli to upload additional artifacts on trigger of release.
=> Updates release/deploy work

CHANGELOG.md, README.md, sleuth/handler.py, sleuth/sleuth/auditor.py, sleuth/sleuth/services.py
- DEBUG envar for additional debugging
- Slack and SNS now have Title and Additional Text (previously only Slack had this)
- Moved notification text to the beginning of the message
- Requirement of Slack or SNS setting to run, Lambda can run without any notifications
=> Cleanup & Fixes

.circleci/config.yml, .pre-commit-config.yaml
Related Pivotal Ticket: https://www.pivotaltracker.com/story/show/176263185
=> Making repo updates

README.md, examples/simple/main.tf, sleuth/handler.py
Updating version string for expire inactive accounts update
=> update to version 1.2.0 in handler and main.tf

README.md, sleuth/sleuth/auditor.py, sleuth/sleuth/services.py
[IAM Sleuth Enhancement: Exclude certain accounts from disable. ](https://www.pivotaltracker.com/story/show/176467745)
Code changes:
Add conditional to not audit keys with KeyAutoExpire tag set to False
Extend User class to have auto_expire attribute, set to 'True' by default
DEBUG output includes AutoExpire value
Update README to mention new user tag
=> SMT- except account expiration

CHANGELOG.md, README.md, examples/simple/main.tf, sleuth/sleuth/auditor.py, sleuth/tests/test_auditor.py, test/terraform_aws_sleuth_simple_test.go
[Add warning if user key is going to expire due to inactivity](https://dp3.atlassian.net/browse/MB-6858)
Code changes:
* Add INACTIVITY_WARNING_AGE variable, which must be set if INACTIVITY_AGE is set
* Update/add tests for new variable
* Update README
=> add inactivity warning

examples/simple/main.tf, sleuth/handler.py
=> update version number

.pre-commit-config.yaml, scripts/build, scripts/release
Changes proposed in this pull request:
- Add shellcheck-py hook
- clear shellcheck errors
=> Add shellcheck hook & fix errors

renovate.json
Changes proposed in this pull request:
- Simplify renovatebot config..  This lines up better with patterns we're using elsewhere
=> Simplify renovatebot config

renovate.json
Changes proposed in this pull request:
- Update renovate schedule to @daily. Closes #232
=> Change schedule to @daily

renovate.json
Changes proposed in this pull request:
- remove the renovatebot schedule
=> Remove the renovate schedule

.envrc, .markdownlintrc, .pre-commit-config.yaml, .terraform-docs.yml, CHANGELOG.md
- **chore(deps): update pre-commit**
- **fix: ignore no shebang**
- **docs: linter**
Trying to fix [this](https://github.com/trussworks/terraform-aws-iam-sleuth/pull/408/files)
=> feat: update pre-commit and use terraform_docs

.github/workflows/pytest.yml, .github/workflows/validate.yml, renovate.json
=> feat: pin shared action

.pre-commit-config.yaml, .terraform-docs.yml
Experiencing some inconsistencies with terraform_docs across repos. This is an experiment.
=> chore: terraform_docs
